# Header
menu:
  首页: /
  #暂时不需要关于: /#blog
  文章: /#blog
  分类: /categories/Brasrom/
  #标签: /tags/New
  #title: 归档
  #layout: page-archive

# Site favicon
favicon: /images/6767.JPG
#你的头像url
avatar: /images/6767.JPG

#Site logo
logo: /images/6767.JPG




# Enable Mathjax
mathjax: true

# Enable awesome-toc
awesome_toc: true

# Enable githubRepoWidget
github_repo_widget: false

# Post wordcount display settings
# Dependencies: https://github.com/willin/hexo-wordcount
post_wordcount:
  item_text: true
  wordcount: true         # 单篇 字数统计
  min2read: true          # 单篇 阅读时长
  totalcount: true #false       # 网站 字数统计
  separated_meta: true

 # visitors count
  counter: true

  # Social
social:
  github: someus


#下方博客评论
#gitment:
#  enable: true # 是否开启gitment评论系统
#  mint: true #
#  count: true # 是否显示评论数
#  lazy: true # 懒加载，设置为ture时需手动展开评论
#  cleanly: true # 是否隐藏'Powered by ...'
#  language: en # 语言，置空则随主题的语言
#  github_user: chenjie040533@163.com # Github用户名
#  github_repo: https://github.com/Brastom/Brastom.github.io.git # 在Github新建一个仓库用于存放评论，这是仓库名
#  client_id: 9c153b88b0d3551a33dc # 注册OAuth Application时生成
#  client_secret: 67c94f2d826c72b8be6d0fd58ad6aad8395d107a # 注册OAuth Application时生成
#  proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
#  redirect_protocol: # Protocol of redirect_uri with force_redirect_protocol when mint enabled
#
#
